### ISSUE TITLE
how to change map container sizes?

### ISSUE THREAD

**Issue by ahmadkam2** [map-ir/mapir-react-component#10]
I want to change map container sizes to my specific values or fit map to parent container element
When I change sizes manually using inspect option of browser, its not work correctly.
Can anyone help me to do this?
Im using map component in ReactJs project.
Thank you.

**Comment by soudabeeh** [comment]
hi,
you can add a class to your Mapir component and change same as bellow
.customClass{
  height: 'custom-height' !important;
  width: 'custom-width' !important;
}

**Comment by ReyhaneMasumi** [comment]
closed due inactivity!
