### ISSUE TITLE
can add searchbar in react component?

### ISSUE THREAD

**Issue by mohammadjaf013** [map-ir/mapir-react-component#11]
i can't add searchbar to component

**Comment by soudabeeh** [comment]
hi,
you can use search api same as this example:

import React, { Component } from 'react'
import './App.css';
import Mapir from 'mapir-react-component';  


const Map = Mapir.setToken({
  transformRequest: url => {
    return {
      url: url,
      headers: {
        "x-api-key":
          "api-key", //Mapir api key

        "Mapir-SDK": "reactjs"
      }
    };
  }
});



export default class App extends Component {

  function(){
    var url=`https://map.ir/search/v2/autocomplete?text='ایت الله بهش'`
    fetch(url,
     { headers: {
        'Content-Type': 'application/json',
        'x-api-key': 'api-key'

    }})
    .then(response=>response.json())
    .then(data=>{console.log(data)})
  }
  render() {

    return (

      <div className="App">

        <Mapir

          center={[51.420470, 35.729054]}
          minZoom={[13]}
          Map={Map}

        onClick={this.function}
        >

          <Mapir.Marker
            coordinates={[51.420470, 35.729054]}
            anchor="bottom"
           
          >
          </Mapir.Marker>


        </Mapir>

      </div >
    )
  }
}

**Comment by mohammadjaf013** [comment]
Thanks
