### ISSUE TITLE
Override component props with defaults

### ISSUE THREAD

**Issue by m-hoseinzadeh** [map-ir/mapir-react-component#3]
setting props (center, containerStyle, ...) does not work ,

https://github.com/map-ir/mapir-react-component/blob/a2c3cda291ccf641478eb416837b3a75b572b4b9/mapir.js#L27

**Comment by ReyhaneMasumi** [comment]
Please upgrade to `mapir-react-component@1.2.4`. We fix this bug. Thanks for your attention and patient.
