### ISSUE TITLE
Name should be MapIr or similar, but not Mapir.

### ISSUE THREAD

**Issue by dehghani-mehdi** [map-ir/mapir-react-component#6]
Hi,

There is no way to read `Mapir` _as you wrote in readme_ as Map IR, you should fix the name, something like `MapIr` or `Map-Ir`.

**Comment by ReyhaneMasumi** [comment]
Hi,
There is no 'Map IR' in readme!
Can you please show us 'Map IR' in English docs?

**Comment by dehghani-mehdi** [comment]
I mentioned `Mapir` not `Map IR`! I think you should read the first post again.

**Comment by dehghani-mehdi** [comment]
Such a behavior was expected from such a company ;)
