### ISSUE TITLE
طراحی بسیار ضعیف و غیر حرفه ای، مستندات کپی شده از مپ باکس

### ISSUE THREAD

**Issue by dehghani-mehdi** [map-ir/mapir-react-component#7]
با سلام،

متاسفم که نقشه توسط شرکت ضعیفی چون شما داره ارائه میشه. 
باز خداروشکر مستندات کامپوننت 
[react-mapbox-gl](https://github.com/alex3165/react-mapbox-gl) 
و خود مپ باکس بوده برای کپی، در غیر این صورت نمی دونم از چه طریقی صفحات مستندات خودتون رو پر می کردید.

به امید وارد شدن شرکت های حرفه ای در چنین زمینه هایی

موفق باشید

**Comment by ReyhaneMasumi** [comment]
Hi,
We always say that our components are base on 'mapbox-gl' and other mapbox web components. So there is no important difference in instructions and documentations.
We also mention in document that every method of 'mapbox-gl' is accessible from our components.
Fortunately, We have a technical support group in our office and if you have a problem to use our services, You can call us at 9 am until 17 pm.
We welcome constructive and polite suggestions and criticisms and will certainly influence them in our work.
Best,
Map.ir

**Comment by dehghani-mehdi** [comment]
سلام مجدد.

چنانچه تفاوت مهمی بین محصول شما و مپ باکس نیست، چرا کدی که بدون ایراد با استفاده از مپ باکس کار می کنه، با کامپوننت شما دچار ایرادات زیادی هست؟
و اصولا چه نیازی به کامپوننت مجزا (که شامل یکسری کدهای سطح پایین) وجود داره؟
و مستندات که یک خط فارسی و مابقی کپی شده از محل دیگه؟ که دارای یکسری موارد غیر مرتبط هم هست.
ضمن اینکه دقیقا در کدوم قسمت اعلام شده که کامپوننت شما بر اساس مپ باکس هست؟ به جز مورد اشاره شده در فایل 
readme
این مخزن؟ که شما اشاره کردید همیشه این موضوع رو اعلام کردید؟!
شما حتی کپی رایت مپ باکس و اپن استریت رو نمایش نمی دید در نقشه.

چنانچه نیاز باشه برای استفاده از کامپوننت شما با بخش فنی شرکت شما تماس تلفنی گرفته بشه، نشان دهنده وجود تفاوت در پیاده سازی و استفاده از کامپوننت شما و مپ باکس است، خلاف انچه شما اعلام کردید.

یکسری ایرادات گرامری هم در نوشته شما وجود داره، پیشنهاد می کنم قبل از پاسخ دادن انگلیسی یک نوشته فارسی کمی برای این موضوع وقت بگذارید.

شاد و پیروز باشید.

**Comment by dehghani-mehdi** [comment]
کمپانی غیر حرفه ای -> رفتار غیر حرفه ای.

**Comment by dehghani-mehdi** [comment]
در این متن به وضوح ادعا شده که مپ حاصل 20 سال تجربه و فلان و بهمان هست، در صورتی شما چیزی جز یک لایه روی مپ باکس و در اصل اپن استریت نیستید

![Screenshot_5](https://user-images.githubusercontent.com/9152330/70431893-44806000-1a93-11ea-9032-3bdca23b1935.png)

پس حداقل نمیخواد اینجا به دروغ اعلام کنید که همیشه اعلام کردید بر مبنای مپ باکس هستید.

**Comment by shiveh** [comment]
> در این متن به وضوح ادعا شده که مپ حاصل 20 سال تجربه و فلان و بهمان هست، در صورتی شما چیزی جز یک لایه روی مپ باکس و در اصل اپن استریت نیستید
> 
> ![Screenshot_5](https://user-images.githubusercontent.com/9152330/70431893-44806000-1a93-11ea-9032-3bdca23b1935.png)
> 
> پس حداقل نمیخواد اینجا به دروغ اعلام کنید که همیشه اعلام کردید بر مبنای مپ باکس هستید.
> 
> قسمت خنده دارش این هست که همون امکانات مپ باکس و سهولت استفاده ازش رو با استفاده از لایه غیر حرفه ای خودتون نابود کردید.

فکر کنم شما موضوع سرویس های نقشه رو با ابزارهای نمایش اشتباه گرفتید. نه تنها ما بلکه بسیاری از ارائه دهنده های سرویس نقشه از ابزارهای قدرتمند در دسترس مانند مپ باکس، لیفلت یا اوپن لیر برای نمایش نقشه استفاده می کنند.
ما در این زمینه هیچوقت ادعایی نداشته و نداریم و همه جا هم اعلام کردیم که از چه ابزارهایی استفاده کردیم.
اون 20 سال سابقه ای که بهش اشاره کردیم کاملا واقعی هست و نتیجه اون عملکرد سرویس های نقشه مپ هستش. بدون شک سرعت سرویس های ما مانند تایل، آدرس دهی و مسیریابی بسیار بالا و در سطح بهترین سرویس های خارجی است و این نتیجه 20 سال کار در حوزه GIS هستش.
با همه این حال اگر پیشنهاد یا انتقادی دارید، دوست داریم با حوصله و صبر، لطف خودتون رو کامل کنید و در جهت بهبود سرویس ها به ما کمک کنید و موضوع رو در جهت کمک به دسترسی و استفاده شما مطرح کنید.

**Comment by dehghani-mehdi** [comment]
یعنی شما دیتابیس خودتون رو از 0 تا 100 خودتون جمع آوری کردید و برای نمایش داده از دیتابیس  خودتون استفاده می کنید و فقط برای نمایش ویژوال نقشه از کتابخانه دیگه ای استفاده می کنید و هیچ استفاده داده ای از اپن استریت نمی کنید؟

در خصوص سرعت هم بارگذاری و پاسخ سریع یک درخواست چه ربطی به داشتن تجربه در زمینه GIS داره رو متوجه نشدم.
سرور های شما باید هم سریعتر پاسخگو باشن به این دلیل که داخل ایران هستند. این هیچ کونه ارتباطی تجربه داشتن شما در GIS یا هر زمینه دیگه ای نمیشه.

در خصوص کمک، در [تیکت دیگری](https://github.com/map-ir/mapir-react-component/issues/6) اعلام کردم که اینکه اسم پکیج و در توضیحات نوشته شده
Mapir
به نظرم منطقی نیست، چون `مپیر` خونده میشه و کسی که ندونه مپ آی آر هستید، اسم رو متوجه نمیشه، مشخصا این در جهت بهبود و در حقیقت حفظ آبرو جامعه برنامه نویسان ایران بوده ولی بدون پاسخ تیکت بسته شده!

**Comment by shiveh** [comment]
> یعنی شما دیتابیس خودتون رو از 0 تا 100 خودتون جمع آوری کردید و برای نمایش داده از دیتابیس خودتون استفاده می کنید و فقط برای نمایش ویژوال نقشه از کتابخانه دیگه ای استفاده می کنید و هیچ استفاده داده ای از اپن استریت نمی کنید؟
> 
> در خصوص سرعت هم بارگذاری و پاسخ سریع یک درخواست چه ربطی به داشتن تجربه در زمینه GIS داره رو متوجه نشدم.
> سرور های شما باید هم سریعتر پاسخگو باشن به این دلیل که داخل ایران هستند. این هیچ گونه ارتباطی تجربه داشتن شما در GIS یا هر زمینه دیگه ای نمیشه.
> 
> در خصوص کمک، در [تیکت دیگری](https://github.com/map-ir/mapir-react-component/issues/6) اعلام کردم که اینکه اسم پکیج و در توضیحات نوشته شده
> Mapir
> به نظرم منطقی نیست، چون `مپیر` خونده میشه و کسی که ندونه مپ آی آر هستید، اسم رو متوجه نمیشه، مشخصا این در جهت بهبود و در حقیقت حفظ آبرو جامعه برنامه نویسان ایران بوده ولی بدون پاسخ تیکت بسته شده!

سرویس‌هایی که مپ ارائه می‌ده از سه قسمت ساخته شده: داده‌های پایه، سرویس‌ها و نمایش
ما در زمینه داده های پایه همون طور که همه جا اعلام کردیم مشارکت کننده در اوپن استریت مپ هستیم. در کنار این اطلاعات ما کلی داده و لایه به داده های پایه اضافه کردیم و در یک فرآیند پیچیده اون ها رو به داده های قابل استفاده جغرافیایی تبدیل کردیم.
در زمینه سرویس های هم بجز استفاده از سرویس های داخلی موضوعات بسیار مهم دیگه ای هم مطرح هست که نشانه اون برتری ما در سرعت و کارایی حتی نسبت به رقبای داخلی هستش.
در زمینه ابزارهای نمایشی هم ما عموما از سرویس های عمومی در دسترس استفاده می کنیم و هیچ هزینه ای هم بابت استفاده از ابزارهای نمایشی از مشتریان دریافت نمی کنیم که مناقشه برانگیز باشه.
اسم پکیج هم یک موضوع داخلی هست و بر اساس سیاست های داخلی و کاربرهای مختلف انتخاب می شه و فکر نمی کنیم هیچ فردی یک سرویس رو از اسم پکیج انتخاب کنه و اسمش تاثیری در عملکردش داشته باشه.

**Comment by dehghani-mehdi** [comment]
در خصوص اسم، مشخصا هر فردی (و قاعدتا) مجموعه ای هر طور دوس داره می تونه اسم محصول خودش رو انتخاب و بنویسه.
موضوع این نیست که چرا پیشنهاد من انجام نشده، موضوع رفتار غیر حرفه ای انجام شده هست که بدون توضیح (تشکر پیش کش) تیکت بسته شده. مخزن های مایکروسافت چنین رفتاری رو ندارن!

در خصوص برتری شما (حداقل در خصوص سرعت پاسخگویی سرورها) نسبت به دیگر عزیزان داخلی، من تجربه کار با دیگر سرویس ها رو ندارم، اما باتوجه به لیست مشتریان شما، روی کاغذ این حرف شما صحیح هست.

اما از دیدگاه یک متخصص آی تی ، این موضوع هیچ ربطی با تجربه دی زمینه جغرافی و جی آی اس نداره و در خصوص کار شما مخصوصا بیشتر سخت افزار مهم هست در سرهت پاسخگویی (و پارامترهای فنی دیگه)

اینکه شما از اطلاعات اپن استریت استفاده می کنید قطعا ایرادی نداره و منطقی هم نیست که چرخ مجدد ابداع بشه و اپن استریت هم اپن سورس هست.

ولی ادعای کاربر پاسخ دهنده اول نسبت به اینکه همیشه اعلام کردید که مپ باکس هستید (در خصوص نمایش یا ....) به نظرم صحیح نیست، چون در سایت تون که من جایی ندیدم اسمی از اپن استریت یا مپ باکس کرده باشید (ممکنه در مستندات فنی باشه).

اصل موضوع من این هست که همین کاری که شما انجام دادید ایرادات زیادی داره، از ایرادات به ظاهر غیر مهم مانند وضعیت بهم ریخته صفحه مستندات
![Screenshot_6](https://user-images.githubusercontent.com/9152330/70436140-db521a00-1a9d-11ea-8fe8-265bfedad2c4.png)

گرفته تا کدهای ضعیف نوشته در همین کامپوننت ری اکت تون.

به نظرم اگر هم میخواستید یک لایه روی مپ باکس باشید، حداقل این کار رو درست انجام بدید نه اینکه شروع به کار مپ باکس نهایت 2 دقیقه زمان لازم داره، نقشه شما بعد از نصف روز باید تلفنی تماس گرفته بشه برای اطلاع از چگونگی نحوه کدنویسی.

**Comment by shiveh** [comment]
> در خصوص اسم، مشخصا هر فردی (و قاعدتا) مجموعه ای هر طور دوس داره می تونه اسم محصول خودش رو انتخاب و بنویسه.
> موضوع این نیست که چرا پیشنهاد من انجام نشده، موضوع رفتار غیر حرفه ای انجام شده هست که بدون توضیح (تشکر پیش کش) تیکت بسته شده. مخزن های مایکروسافت چنین رفتاری رو ندارن!
> 
> در خصوص برتری شما (حداقل در خصوص سرعت پاسخگویی سرورها) نسبت به دیگر عزیزان داخلی، من تجربه کار با دیگر سرویس ها رو ندارم، اما باتوجه به لیست مشتریان شما، روی کاغذ این حرف شما صحیح هست.
> 
> اما از دیدگاه یک متخصص آی تی ، این موضوع هیچ ربطی با تجربه در زمینه جغرافی و جی آی اس نداره و در خصوص کار شما مخصوصا بیشتر سخت افزار مهم هست در سرعت پاسخگویی (و خب پارامترهای فنی دیگه)
> 
> اینکه شما از اطلاعات اپن استریت استفاده می کنید قطعا ایرادی نداره و منطقی هم نیست که چرخ مجدد ابداع بشه و اپن استریت هم اپن سورس هست.
> 
> ولی ادعای کاربر پاسخ دهنده اول نسبت به اینکه همیشه اعلام کردید که بر پایه مپ باکس هستید (در خصوص نمایش یا ....) به نظرم صحیح نیست، چون در سایت تون که من جایی ندیدم اسمی از اپن استریت یا مپ باکس کرده باشید (ممکنه در مستندات فنی باشه).
> 
> اصل موضوع من این هست که همین کاری که شما انجام دادید ایرادات زیادی داره، از ایرادات به ظاهر غیر مهم مانند وضعیت بهم ریخته صفحه مستندات
> ![Screenshot_6](https://user-images.githubusercontent.com/9152330/70436140-db521a00-1a9d-11ea-8fe8-265bfedad2c4.png)
> 
> گرفته تا کدهای ضعیف نوشته در همین کامپوننت ری اکت تون.
> 
> به نظرم اگر هم میخواستید یک لایه روی مپ باکس باشید، حداقل این کار رو درست انجام بدید نه اینکه شروع به کار مپ باکس نهایت 2 دقیقه زمان لازم داره، نقشه شما بعد از نصف روز باید تلفنی تماس گرفته بشه برای اطلاع از چگونگی نحوه کدنویسی.

ممنون که با دقت بیشتری موضوع رو مشخص کردید
ما توی مستندات فنی و خود نقشه هر جا شده اسم OSM و مپ باکس رو آوردیم
![image](https://user-images.githubusercontent.com/42200056/70436581-e0fc2f80-1a9e-11ea-8846-ae503923fadc.png)

در مورد مستندات هم به نسبت مپ باکس ادعایی نداریم و سعی داریم روز به روز مستندات بهتر و دقیقتری رو ایجاد کنیم. این همون جایی هست که نیاز به بازخورد کاربران داریم. هر چه دقیقتر به ما جزییات بدید ما می تونیم بهتر و سریعتر مستندات رو ارتقا بدیم. با توجه به این موضوع دوست داریم مشکل دقیق مستندات رو از شما بشنویم تا دقیقا همون بخش رو بهبود بدیم.

**Comment by dehghani-mehdi** [comment]
@shiveh 
پاسخ قبلی خودم رو ادیت کردم و مورده دیگری رو بهش اضافه کردم.

در خصوص مستندات هم تا زمان کامل شدن می شد که لینک به صفحه اصلی در مپ باکس بدید که پیدا کردن 
موارد راحتتر باشه
صرف کپی کردن موارد و نوشتن یک جمله فارسی، هیچ کمکی به برنامه نویس نمی کنه، من به شخصه به هیچ عنوان نتونستم موارد مورد نیاز رو پیدا کنم و منبع اصلی همون مستندات مپ باکس هست برای من.

**Comment by dehghani-mehdi** [comment]
علیرغم صرف زمان برای پیاده سازی نقشه با استفاده از محصول شما و عدم رسیدن به نتیجه مطلوب با توجه به کاستی های محصول شما، تصمیم گرفتیم که از مپ باکس استفاده کنیم.

امیدوارم که تصمیماتی اتخاذ کنید که در آینده بتونیم از خدمات شما در محصولات خودمون استفاده کنیم.

موفق باشید

**Comment by shiveh** [comment]
> علیرغم صرف زمان برای پیاده سازی نقشه با استفاده از محصول شما و عدم رسیدن به نتیجه مطلوب با توجه به کاستی های محصول شما، تصمیم گرفتیم که از مپ باکس استفاده کنیم.
> 
> امیدوارم که تصمیماتی اتخاذ کنید که در آینده بتونیم از خدمات شما در محصولات خودمون استفاده کنیم.
> 
> موفق باشید
> 
> پ.ن: اگر برنامه نویسی در حال مطالعه این نوشته هست و تصمیم به پیاده سازی مپ آی آر در پروژه خودش رو داره، توصیه من این هست که تنها در صورتی از مپ آی آر استفاده کنید که بخواهید فقط مپ ساده، بدون هیچ امکان اضافی رو در پروژه خودتون نمایش بدید. در غیر اینصورت حتما قبل از وقت گذاشتن بررسی کنید که آیا این محصول توانایی انجام کار مورد نظر شما (مخصوصا به صورت اصولی) رو داره یا نه.
> کاری که در مپ باکس تنها 5 دقیقه زمان میبره، 3 روز با مپ آی ار انجام نشد. تیم ما تیم غیر حرفه ای نیست و شخص بنده فقط در خصوص ری اکت بیش از 4 سال به صورت حرفه ای تجربه کاری دارم. اما امکان استفاده از این نقشه در ری اکت به صورت اصولی و بدون نوشتن کدهای اضافی (به دلیل ضعف شدید مپ آی ار) غیر ممکن هست.
> _بررسی سایت و [کدهای](https://github.com/map-ir/mapir-react-component/blob/master/components/source.js) [نوشته شده](https://github.com/map-ir/mapir-react-component/blob/master/mapir.js) به خوبی گویای عدم حرفه ای بودن کامپوننت و کتابخانه های مرتبط با این نقشه هست._

امیدوارم در با استفاده از مپباکس به اهداف خودتون برسید و موفق باشید.
ما هم سعی می کنیم روز به روز سرویس ها و مستندات راهنما رو بهبود بدیم.
در مورد سرویس های نقشه هم بعید می دونم مپباکس جایگزین مناسبی برای سرویس هایی مانند reverse، distance matrix و یا ETA باشه.
با این حال برای شما آرزوی موفقیت داریم

**Comment by tahagit** [comment]
کار نمیکنه اصلا چرا بهونه میارید؟؟؟!!!!!!!

**Comment by ReyhaneMasumi** [comment]
@tahagit سلام. لطفا مثال هایی که در 
[https://support.map.ir/developers/components/reactjs/1-3-0/examples/](url)
 وجود دارند را ملاحظه بفرمایید. همگی نمونه پروژه در
 stackblitz
 دارند. لطفا دقیق تر مشخص کنید که چه اروری وجود داره تا ما بتونیم کمکتون کنیم
