### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by hiradary** [map-ir/mapir-react-component#8]
Failed to compile.

postcss-svgo: Error in parsing SVG: Unmatched closing tag: svg
Line: 0
Column: 109
Char: >

**Steps to reproduce**
1 - Install the latest version (1.6.2 for me at the moment)
2 - Set up the basic example
3 - Run "yarn build" to create the production build.

**Comment by hiradary** [comment]
A friend of mine did this: https://github.com/mrlaseptima/mapir-react-component/commit/b42b97bd44229396671a9498449061310c58e5b5

It's actually working now

**Comment by soudabeeh** [comment]
Please upgrade to mapir-react-component@1.6.3. We fix this bug. Thanks for your attention and patient.

**Comment by hiradary** [comment]
Thanks for your help!
