### ISSUE TITLE
Mapbox.framework  doesent exist in ios file in mapir-mapbox

### ISSUE THREAD

**Issue by amirmn72** [map-ir/mapir-react-component#9]
برای نصب  آی اٌ اس داخل راهنمایی نوشتین که فایل  
mapbox.framework
 رو توی باینری اضافه کنم اما همچین فایلی وجود نداره واسه من تو  فایل
node_modules/mapire-mapbox/ios

**Comment by ReyhaneMasumi** [comment]
سلام
لطفا [لینک](https://support.map.ir/developers/reactnative/2-0-5/installation-2/.) را مشاهده نمایید.
برای دانلود 
mapbox.framework
لازم است که بسته ی
wget
روی سیستم عامل 
Mac
نصب باشد. در غیر این صورت فایل موردنظر دانلود نخواهد شد

**Comment by ReyhaneMasumi** [comment]
closed for inactivity.
